### ISSUE TITLE
wgpu error: Validation Error

### ISSUE THREAD

**Issue by katopz** [alexichepura/bevy_garage#90]
## Problem
Refer to https://github.com/bevyengine/bevy/issues/9389

```
2023-10-12T04:06:46.819690Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (2)' panicked at /Users/katopz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `main_texture_a`
    Dimension X value 4294967295 exceeds the limit of 16384


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::prepare_view_targets`!
thread 'main' panicked at /Users/katopz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.0/src/pipelined_rendering.rs:135:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Solution
I did upgrade to `bevy 0.11.3` and it work fine on my Mac Intel but not sure about the other target.

So i'm not sure to make a PR. 🫣

**Comment by alexichepura** [comment]
I did cargo update and pushed it. Works on mac m1.
Hmm should i gitignore cargo.lock? I will let my head to sleep with this idea for a day) But now I think I should remove lock.

I will check later on other platforms. Then will probably just close this issue 🤷
Thanks!

**Comment by katopz** [comment]
IMHO lock is fine to me at least we can track down what went wrong.
Feel free to close when you done.

Cheers!
