### ISSUE TITLE
localhost 404 for assets

### ISSUE THREAD

**Issue by katopz** [alexichepura/bevy_garage#91]
## Problems
- `wasm/assets` not symbolic link on macOS intel.

## Workaround
- Remove old `assets` file? and make a symbolic link before serve.
```
rm ./wasm/assets
ln -s ./assets ./wasm/assets
. ./wasm.sh
```

Maybe only me but I will log here so ppl can search and see a workaround. Feel free to close it.

**Comment by alexichepura** [comment]
Thanks again) Totally my mistake.
```sh
readlink ./wasm/assets # outputs /Users/alexi/w/bevy_garage/assets
```
Pushed fix to main.
